### ISSUE TITLE
External IP address of service load balancer does not update status

### ISSUE THREAD

**Issue by Gerrit91** [metal-stack/metal-ccm#10]
There is a service in the cluster of type load balancer, metal-ccm will properly acquire the IP at the metal-api and write it into the service's load balancer status field:

```
k get svc -o yaml ingress-nginx 
apiVersion: v1
kind: Service
metadata:
  ...
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
  name: ingress-nginx
  namespace: ingress-nginx
  ...
spec:
  clusterIP: 10.244.73.145
  externalTrafficPolicy: Local
  healthCheckNodePort: 30904
  ports:
  - name: http
    nodePort: 30469
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    nodePort: 31565
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 185.153.67.128
```

When you do the following:

- Delete this service again
- (metal-ccm releases the IP)
- (Someone else acquires the IP)
- And you recreate this service

Then:
- metal-ccm will acquire a new IP address
- The service will get the old IP address instead of the new address
- The old IP is not in the metallb config anymore, so this works fine
- The service refuses to take any other IP address even when trying to set it explicitly via the `LoadBalancerIP` field

```
k get svc
NAME            TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
ingress-nginx   LoadBalancer   10.244.73.145   <pending>     80:30469/TCP,443:31565/TCP   13m
```

```
k get svc -o yaml ingress-nginx 
apiVersion: v1
kind: Service
metadata:
  ...
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
  name: ingress-nginx
  namespace: ingress-nginx
  ...
spec:
  clusterIP: 10.244.73.145
  externalTrafficPolicy: Local
  healthCheckNodePort: 30904
  loadBalancerIP: 185.153.67.234
  ports:
  - name: http
    nodePort: 30469
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    nodePort: 31565
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
```
