### ISSUE TITLE
[v0.9.2] - metallb configmap is stale with static ip adresses

### ISSUE THREAD

**Issue by mwennrich** [metal-stack/metal-ccm#104]
```
    Message:               ControlPlane extension (shoot--test--fra-equ01/fra-equ01) reports failing health check: metallb configmap is stale / erroneous, next speaker reload may interrupt workload traffic.
    Reason:                ControlPlaneUnhealthyReport
    Status:                False
    Type:                  SystemComponentsHealthy

```

```
controller-5479f76bdc-bjwgw controller {"caller":"pool_controller.go:81","controller":"PoolReconciler","error":"CIDR \"212.34.83.22/32\" in pool \"internet-static\" overlaps with already defined CIDR \"212.34.83.22/32\"","level":"error","ts":"2024-10-29T08:53:20Z"}
```

```yaml
  apiVersion: metallb.io/v1beta1
  kind: IPAddressPool
  metadata:
    name: internet-ephemeral
    namespace: metallb-system
  spec:
    addresses:
    - 212.34.83.16/32
    - 212.34.83.20/32
    - 212.34.83.22/32
    - 212.34.83.3/32

  apiVersion: metallb.io/v1beta1
  kind: IPAddressPool
  metadata:
    name: internet-static
    namespace: metallb-system
  spec:
    addresses:
    - 212.34.83.22/32
```
